'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';

interface Startup {
  name: string;
  description: string;
  website: string;
}

export interface Pathway {
  name: string;
  icon: string;
  connection: string;
  startups: Startup[];
  skills: string[];
  firstSteps: string[];
}

interface StudentInterests {
  topInterests: string[];
  contentThemes: string[];
  categories: Record<string, number>;
  platform: string;
}

export interface PathwaysData {
  id: string;
  profile_id: string;
  student_interests: StudentInterests;
  pathways: Pathway[];
  created_at: string;
  updated_at: string;
}

interface UsePathwaysOptions {
  autoGenerate?: boolean;
}

export function usePathways({ autoGenerate = false }: UsePathwaysOptions = {}) {
  const router = useRouter();
  const [data, setData] = useState<PathwaysData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [choosingIndex, setChoosingIndex] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const fetchPathways = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch('/api/startup-pathways');
      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Failed to fetch pathways');
      }

      setData(result.pathways);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  }, []);

  const generatePathways = useCallback(async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const response = await fetch('/api/startup-pathways', {
        method: 'POST',
      });
      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Failed to generate pathways');
      }

      setData(result.pathways);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsGenerating(false);
    }
  }, []);

  const choosePathway = useCallback(async (pathwayIndex: number) => {
    if (!data) return;

    const pathway = data.pathways[pathwayIndex];
    setChoosingIndex(pathwayIndex);
    setError(null);

    try {
      const response = await fetch('/api/startup-pathways/choose', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          pathwayId: data.id,
          pathwayIndex,
          pathway,
        }),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Failed to create project');
      }

      // Redirect to mobile chosen confirmation
      router.push(`/m/pathways/${data.id}/chosen?project=${result.project.id}&name=${encodeURIComponent(pathway.name)}`);
    } catch (err: any) {
      setError(err.message);
      setChoosingIndex(null);
    }
  }, [data, router]);

  // Initial fetch
  useEffect(() => {
    fetchPathways();
  }, [fetchPathways]);

  // Auto-generate if requested and no existing pathways
  useEffect(() => {
    if (autoGenerate && !isLoading && !data && !hasAutoGenerated && !isGenerating) {
      setHasAutoGenerated(true);
      generatePathways();
    }
  }, [autoGenerate, isLoading, data, hasAutoGenerated, isGenerating, generatePathways]);

  return {
    // Data
    data,
    pathways: data?.pathways || [],
    interests: data?.student_interests || null,

    // State
    isLoading,
    isGenerating,
    choosingIndex,
    error,

    // Actions
    fetchPathways,
    generatePathways,
    choosePathway,

    // Helpers
    hasPathways: !!data?.pathways?.length,
    isChoosing: choosingIndex !== null,
  };
}
